package com.advantys.brsmovilidaderp.Domain.Models

import com.advantys.brsmovilidaderp.Data.DataBase.Entities.CabPedidos_Entity
import java.util.Date

class CabPedido (
    var serie: String? = null,
    var pedido: Int? = null,
    var centro: Short? = null,
    var cliente: Int? = null,
    var delegacion: Short? = null,
    var clientefiscal: Int? = null,
    var delegacionfiscal: Short? = null,
    var formapago: Short? = null,
    var cpreventa: Date? = null,
    var reparto: Date? = null,
    var rutaventa: String? = null,
    var secuventa: String? = null,
    var rutareparto: String? = null,
    var secureparto: String? = null,
    var porcdto: Float? = null,
    var facturable: String? = null,
    var tipooperacion: Short? = null,
    var seriehoja: String? = null,
    var hoja: Int? = null,
    var sureferencia: String? = null,
    var totalpedido:Float?= null,
    var enviado: Boolean? = false,
    var tiporeparto: String? = null,
    var apldtopor: Boolean? = null,
    var fabricante: Short? = null,
    var npreventa: Int? = null,
    var seriealbaran: String? = null,
    var albaran: Int? = null,
    var fechaalbaran: Date? = null,
    var seriefactura: String? = null,
    var factura: Int? = null,
    var fechafactura: Date? = null,
    var notas: String? = null,
    var carga: Short? = null,
    var impreso: Boolean? = null,
    var pendientevalidar: String? = null,
    var importado: Boolean? = null,
    var tarifa: Int? = null,
    var ejercicio: Int? = null,
    var ejerhoja: Int? = null,
    var ejeralbaran: Int? = null,
    var ejerfactura: Int? = null,
    var situacion: Int? = 0,
    var repetir: Date? = null,
    var dnidestinatario: String? = null,
    var nombredestinatario: String? = null
)
fun CabPedidos_Entity.toDomain() = CabPedido( serie, pedido, centro, cliente, delegacion, clientefiscal, delegacionfiscal, formapago, cpreventa, reparto, rutaventa, secuventa, rutareparto, secureparto, porcdto, facturable,tipooperacion, seriehoja, hoja, sureferencia, totalpedido,enviado, tiporeparto, apldtopor, fabricante, npreventa, seriealbaran, albaran, fechaalbaran, seriefactura, factura, fechafactura, notas, carga, impreso, pendientevalidar, importado, tarifa, ejercicio, ejerhoja, ejeralbaran, ejerfactura,situacion, repetir, dnidestinatario, nombredestinatario)